// Menu data for the pizza restaurant - Based on actual menu

export interface PizzaSize {
  size: 'Small' | 'Medium' | 'Large';
  price: number;
}

export interface MenuItem {
  id: string;
  name: string;
  description: string;
  prices?: PizzaSize[];
  price?: number;
  image?: string;
  category?: string;
  featured?: boolean;
  isVegetarian?: boolean;
}

export const menuData = {
  pizzas: [
    {
      id: 'cheese',
      name: 'Cheese Pizza',
      description: 'Classic mozzarella cheese on our signature tomato sauce',
      prices: [
        { size: 'Small', price: 12.99 },
        { size: 'Medium', price: 15.99 },
        { size: 'Large', price: 18.99 },
      ],
      image: 'https://images.unsplash.com/photo-1674526498355-e20c280bc6ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGVlc2UlMjBwaXp6YSUyMG1venphcmVsbGF8ZW58MXx8fHwxNzcyMjY4NDExfDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'classic',
    },
    {
      id: 'white',
      name: 'White Pizza',
      description: 'Ricotta cheese, mozzarella & Pecorino Romano - no sauce',
      prices: [
        { size: 'Small', price: 13.99 },
        { size: 'Medium', price: 16.99 },
        { size: 'Large', price: 19.99 },
      ],
      image: 'https://images.unsplash.com/photo-1559918080-6d0657ceaf61?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aGl0ZSUyMHBpenphJTIwcmljb3R0YXxlbnwxfHx8fDE3NzIyNjkyNzR8MA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'specialty',
      isVegetarian: true,
    },
    {
      id: 'petes-special',
      name: "Pete's Special",
      description: 'Loaded with a variety of premium meats and fresh vegetables',
      prices: [
        { size: 'Small', price: 17.99 },
        { size: 'Medium', price: 20.99 },
        { size: 'Large', price: 23.99 },
      ],
      image: 'https://images.unsplash.com/photo-1681567604770-0dc826c870ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXByZW1lJTIwcGl6emElMjB0b3BwaW5nc3xlbnwxfHx8fDE3NzIyNTQ5NzJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'specialty',
      featured: true,
    },
    {
      id: 'blackened-chicken',
      name: 'Blackened Chicken',
      description: 'Spicy blackened chicken, mozzarella, and our signature sauce',
      prices: [
        { size: 'Small', price: 15.99 },
        { size: 'Medium', price: 18.99 },
        { size: 'Large', price: 21.99 },
      ],
      image: 'https://images.unsplash.com/photo-1650645120743-d4c61a44ea0f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwcGl6emElMjBibGFja2VuZWR8ZW58MXx8fHwxNzcyMjY5Mjc0fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'specialty',
    },
    {
      id: 'buffalo-chicken-ranch',
      name: 'Buffalo Chicken Ranch',
      description: 'Buffalo chicken, ranch dressing, and melted mozzarella',
      prices: [
        { size: 'Small', price: 16.99 },
        { size: 'Medium', price: 19.99 },
        { size: 'Large', price: 22.99 },
      ],
      image: 'https://images.unsplash.com/photo-1734769484424-36b99dd84818?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidWZmYWxvJTIwY2hpY2tlbiUyMHBpenphfGVufDF8fHx8MTc3MjI2OTI3OHww&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'specialty',
    },
    {
      id: 'bbq-chicken',
      name: 'BBQ Chicken Pizza',
      description: 'Tender chicken with tangy BBQ sauce and red onions',
      prices: [
        { size: 'Small', price: 15.99 },
        { size: 'Medium', price: 18.99 },
        { size: 'Large', price: 21.99 },
      ],
      image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYnElMjBjaGlja2VuJTIwcGl6emF8ZW58MXx8fHwxNzcyMjA3OTc3fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'specialty',
    },
    {
      id: 'meat-pie',
      name: 'Meat Pie',
      description: "Loaded with all your favorite meats - a carnivore's dream",
      prices: [
        { size: 'Small', price: 16.99 },
        { size: 'Medium', price: 19.99 },
        { size: 'Large', price: 22.99 },
      ],
      image: 'https://images.unsplash.com/photo-1705286324371-d6a6d9519dc2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWF0JTIwbG92ZXJzJTIwcGl6emF8ZW58MXx8fHwxNzcyMjU5NTUxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'specialty',
    },
    {
      id: 'your-bro',
      name: 'Your Bro Pizza',
      description: 'The "Bro" Salute - fresh broccoli and grilled chicken',
      prices: [
        { size: 'Small', price: 16.99 },
        { size: 'Medium', price: 19.99 },
        { size: 'Large', price: 21.99 },
      ],
      image: 'https://images.unsplash.com/photo-1615595190084-c048920f5b03?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwYnJvY2NvbGklMjBwaXp6YXxlbnwxfHx8fDE3NzIyNjkyNzV8MA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'specialty',
    },
    {
      id: 'the-works',
      name: 'The "Works"',
      description: 'Everything! Pepperoni, sausage, peppers, onions, mushrooms, and more',
      prices: [
        { size: 'Small', price: 18.99 },
        { size: 'Medium', price: 21.99 },
        { size: 'Large', price: 24.99 },
      ],
      image: 'https://images.unsplash.com/photo-1681567604770-0dc826c870ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXByZW1lJTIwcGl6emElMjB0b3BwaW5nc3xlbnwxfHx8fDE3NzIyNTQ5NzJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'specialty',
      featured: true,
    },
  ],
  subs: [
    {
      id: 'meatball',
      name: 'Meatball',
      description: 'House-made meatballs with marinara and melted mozzarella',
      price: 9.95,
      image: 'https://images.unsplash.com/photo-1659477483002-c5d0515b58d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWF0YmFsbCUyMHN1YiUyMHNhbmR3aWNofGVufDF8fHx8MTc3MjI2OTI3OXww&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'subs',
    },
    {
      id: 'bbq-chicken-philly',
      name: 'BBQ Chicken Philly',
      description: 'BBQ chicken with sautéed onions and green peppers',
      price: 10.95,
      image: 'https://images.unsplash.com/photo-1760390952092-03cf0a020f25?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwcGhpbGx5JTIwc2FuZHdpY2h8ZW58MXx8fHwxNzcyMjY5Mjc5fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'subs',
    },
    {
      id: 'ham-italian',
      name: 'Ham Italian',
      description: 'Ham, salami, pepperoni, provolone with lettuce, tomato, onion',
      price: 9.95,
      image: 'https://images.unsplash.com/photo-1749513762144-8991c898d95c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpdGFsaWFuJTIwc3ViJTIwc2FuZHdpY2h8ZW58MXx8fHwxNzcyMjY5Mjc5fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'subs',
    },
    {
      id: 'steak-cheese',
      name: 'Steak & Cheese',
      description: 'Shaved steak with melted cheese, lettuce, tomato and onions',
      price: 8.50,
      image: 'https://images.unsplash.com/photo-1677367306400-d090b5ab52d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGVhayUyMGNoZWVzZSUyMHN1YnxlbnwxfHx8fDE3NzIyNjkyNzl8MA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'subs',
    },
    {
      id: 'buffalo-chicken',
      name: 'Buffalo Chicken',
      description: 'Spicy buffalo chicken with ranch or blue cheese',
      price: 10.95,
      image: 'https://images.unsplash.com/photo-1722239317377-90a8768791a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidWZmYWxvJTIwY2hpY2tlbiUyMHNhbmR3aWNofGVufDF8fHx8MTc3MjI2OTI4MHww&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'subs',
    },
    {
      id: 'chicken-parm',
      name: 'Chicken Parmigiana',
      description: 'Breaded chicken cutlet with marinara and melted mozzarella',
      price: 10.95,
      image: 'https://images.unsplash.com/photo-1608872689366-4cbcf0c7e72c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwcGFybSUyMHN1YnxlbnwxfHx8fDE3NzIyNjkyODB8MA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'subs',
    },
    {
      id: 'blackened-chicken-sub',
      name: 'Blackened Chicken',
      description: 'Spicy blackened chicken with lettuce, tomato, onions',
      price: 9.95,
      image: 'https://images.unsplash.com/photo-1643111998354-07e7a780c92b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxibGFja2VuZWQlMjBjaGlja2VuJTIwc2FuZHdpY2h8ZW58MXx8fHwxNzcyMjY5MjgwfDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'subs',
    },
    {
      id: 'tuna',
      name: 'Tuna',
      description: 'Solid white tuna with lettuce and topped with lettuce and tomato',
      price: 7.95,
      image: 'https://images.unsplash.com/photo-1757961048411-73703e333d25?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0dW5hJTIwc3ViJTIwc2FuZHdpY2h8ZW58MXx8fHwxNzcyMjY5MjgwfDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'subs',
    },
    {
      id: 'italian-sausage',
      name: 'Italian Sausage',
      description: 'Italian sausage with sautéed onions and green peppers',
      price: 9.95,
      image: 'https://images.unsplash.com/photo-1765646663878-3e81e6800e2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpdGFsaWFuJTIwc2F1c2FnZSUyMHNhbmR3aWNofGVufDF8fHx8MTc3MjI2OTI4MXww&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'subs',
    },
    {
      id: 'stromboli',
      name: 'Stromboli with Sauce',
      description: 'Ham, salami, pepperoni, cheese rolled and baked, served with sauce',
      price: 7.95,
      image: 'https://images.unsplash.com/photo-1582034986517-30d163aa1da9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxncmlsbGVkJTIwY2hpY2tlbiUyMGNhZXNhcnxlbnwxfHx8fDE3NzIyNjkyODF8MA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'subs',
    },
    {
      id: 'hamburger',
      name: 'Hamburger on Kaiser Roll',
      description: '1/4 lb Angus beef hamburger with lettuce, tomato, pickles & onions',
      price: 11.95,
      image: 'https://images.unsplash.com/photo-1760390952092-03cf0a020f25?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaGlsbHklMjBjaGVlc2VzdGVhayUyMHNhbmR3aWNofGVufDF8fHx8MTc3MjI2OTI4MXww&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'subs',
    },
  ],
  friedChicken: [
    {
      id: 'individual-2pc',
      name: '2 Piece Dinner',
      description: 'Individual dinner with 2 pieces of chicken',
      price: 9.95,
      image: 'https://images.unsplash.com/photo-1764018292116-003fd7d1a0ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmllZCUyMGNoaWNrZW4lMjBwaWVjZXN8ZW58MXx8fHwxNzcyMjY5Mjg0fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'fried-chicken',
    },
    {
      id: 'individual-3pc',
      name: '3 Piece Dinner',
      description: 'Individual dinner with 3 pieces of chicken',
      price: 10.50,
      image: 'https://images.unsplash.com/photo-1764018292116-003fd7d1a0ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmllZCUyMGNoaWNrZW4lMjBwaWVjZXN8ZW58MXx8fHwxNzcyMjY5Mjg0fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'fried-chicken',
    },
    {
      id: 'individual-4pc',
      name: '4 Piece Dinner',
      description: 'Individual dinner with 4 pieces of chicken',
      price: 12.99,
      image: 'https://images.unsplash.com/photo-1764018292116-003fd7d1a0ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmllZCUyMGNoaWNrZW4lMjBwaWVjZXN8ZW58MXx8fHwxNzcyMjY5Mjg0fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'fried-chicken',
    },
    {
      id: 'white-2pc',
      name: '2 Piece All White',
      description: 'All white meat dinner',
      price: 11.99,
      image: 'https://images.unsplash.com/photo-1764018292116-003fd7d1a0ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmllZCUyMGNoaWNrZW4lMjBwaWVjZXN8ZW58MXx8fHwxNzcyMjY5Mjg0fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'fried-chicken',
    },
    {
      id: 'white-3pc',
      name: '3 Piece All White',
      description: 'All white meat dinner',
      price: 13.99,
      image: 'https://images.unsplash.com/photo-1764018292116-003fd7d1a0ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmllZCUyMGNoaWNrZW4lMjBwaWVjZXN8ZW58MXx8fHwxNzcyMjY5Mjg0fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'fried-chicken',
    },
    {
      id: 'white-4pc',
      name: '4 Piece All White',
      description: 'All white meat dinner',
      price: 15.99,
      image: 'https://images.unsplash.com/photo-1764018292116-003fd7d1a0ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmllZCUyMGNoaWNrZW4lMjBwaWVjZXN8ZW58MXx8fHwxNzcyMjY5Mjg0fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'fried-chicken',
    },
    {
      id: 'bucket-8pc',
      name: '8 Piece Bucket',
      description: 'Perfect for sharing',
      price: 19.95,
      image: 'https://images.unsplash.com/photo-1764018292116-003fd7d1a0ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmllZCUyMGNoaWNrZW4lMjBwaWVjZXN8ZW58MXx8fHwxNzcyMjY5Mjg0fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'fried-chicken',
    },
    {
      id: 'bucket-12pc',
      name: '12 Piece Bucket',
      description: 'Great for the family',
      price: 24.99,
      image: 'https://images.unsplash.com/photo-1764018292116-003fd7d1a0ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmllZCUyMGNoaWNrZW4lMjBwaWVjZXN8ZW58MXx8fHwxNzcyMjY5Mjg0fDA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'fried-chicken',
    },
    {
      id: 'jojos',
      name: "Jo Jo's",
      description: 'Seasoned potato wedges (8 piece)',
      price: 7.95,
      image: 'https://images.unsplash.com/photo-1717294978892-cef673e1d17b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVuY2glMjBmcmllcyUyMGdvbGRlbnxlbnwxfHx8fDE3NzIyNjkyODZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'fried-chicken',
    },
    {
      id: 'jojos-16',
      name: "Jo Jo's",
      description: 'Seasoned potato wedges (16 piece)',
      price: 9.95,
      image: 'https://images.unsplash.com/photo-1717294978892-cef673e1d17b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVuY2glMjBmcmllcyUyMGdvbGRlbnxlbnwxfHx8fDE3NzIyNjkyODZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
      category: 'fried-chicken',
    },
  ],
  wings: [
    {
      id: 'wings-10',
      name: '10 Wings',
      description: 'Served mild, hot, BBQ, Teriyaki, BBQ Blackened, or Teriyaki Blackened',
      price: 12.95,
      category: 'wings',
    },
    {
      id: 'wings-20',
      name: '20 Wings',
      description: 'Served mild, hot, BBQ, Teriyaki, BBQ Blackened, or Teriyaki Blackened',
      price: 24.95,
      category: 'wings',
    },
    {
      id: 'wings-50',
      name: '50 Wings',
      description: 'Served mild, hot, BBQ, Teriyaki, BBQ Blackened, or Teriyaki Blackened',
      price: 59.95,
      category: 'wings',
    },
    {
      id: 'wings-100',
      name: '100 Wings',
      description: 'Served mild, hot, BBQ, Teriyaki, BBQ Blackened, or Teriyaki Blackened',
      price: 119.95,
      category: 'wings',
    },
    {
      id: 'boneless-8',
      name: '8 Boneless Wings',
      description: 'Choice of sauces',
      price: 9.95,
      category: 'wings',
    },
    {
      id: 'boneless-12',
      name: '12 Boneless Wings',
      description: 'Choice of sauces',
      price: 12.95,
      category: 'wings',
    },
  ],
  pasta: [
    {
      id: 'spaghetti-meatballs',
      name: 'Spaghetti w/ Meatballs',
      description: 'Served with bread and garlic bread',
      price: 10.99,
      image: 'spaghetti meatballs',
      category: 'pasta',
    },
    {
      id: 'baked-spaghetti',
      name: 'Baked Spaghetti Smothered w/Cheese',
      description: 'Served with bread and garlic bread',
      price: 12.99,
      image: 'baked spaghetti cheese',
      category: 'pasta',
      isVegetarian: true,
    },
    {
      id: 'baked-spaghetti-meatballs',
      name: 'Baked Spaghetti Smothered w/Cheese & Meatballs',
      description: 'Served with bread and garlic bread',
      price: 13.99,
      image: 'baked spaghetti meatballs',
      category: 'pasta',
    },
    {
      id: 'lasagna',
      name: 'Lasagna',
      description: 'Served with bread and garlic bread',
      price: 15.99,
      image: 'lasagna italian',
      category: 'pasta',
    },
  ],
  calzones: [
    {
      id: 'cheese-calzone',
      name: 'Cheese Calzone',
      description: 'With 2 choices of pizza toppings & cheese blend. Additional items $1.99 each',
      price: 9.99,
      image: 'calzone cheese',
      category: 'calzone',
    },
  ],
  salads: [
    {
      id: 'greek',
      name: 'Greek Salad',
      description: 'Feta, lettuce, tomato, onions, pepperoni, olives, cucumbers, Greek dressing',
      price: 11.99,
      image: 'greek salad feta',
      category: 'salad',
      isVegetarian: true,
    },
    {
      id: 'caesar',
      name: 'Caesar Salad',
      description: 'Romaine, parmesan, croutons with Caesar dressing',
      price: 9.99,
      image: 'caesar salad romaine',
      category: 'salad',
      isVegetarian: true,
    },
    {
      id: 'antipasto',
      name: 'Antipasto Salad',
      description: 'Ham, salami, pepperoni, cheese, peppers, olives, lettuce, tomato, onions',
      price: 11.99,
      image: 'antipasto salad italian',
      category: 'salad',
    },
    {
      id: 'chicken-salad',
      name: 'Chicken Salad (Fried, Baked or Blackened)',
      description: 'Chicken, cheese, lettuce, tomato, cucumbers, peppers',
      price: 12.99,
      image: 'chicken salad grilled',
      category: 'salad',
    },
    {
      id: 'tuna-salad',
      name: 'Tuna Salad',
      description: 'Solid white tuna with lettuce, tomatoes, cucumbers',
      price: 11.99,
      image: 'tuna salad',
      category: 'salad',
    },
    {
      id: 'garden',
      name: 'Garden Salad',
      description: 'Lettuce, tomato, cucumber, green peppers, red onions, choice of dressing',
      price: 6.95,
      image: 'garden salad fresh',
      category: 'salad',
      isVegetarian: true,
    },
  ],
  appetizers: [
    {
      id: 'fried-mushrooms',
      name: 'Fried Mushrooms',
      description: 'Breaded and fried to perfection',
      price: 8.99,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'fried-green-beans',
      name: 'Fried Green Beans',
      description: 'Crispy fried green beans',
      price: 6.99,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'fried-ravioli',
      name: 'Fried Ravioli',
      description: 'Breaded ravioli with marinara',
      price: 6.99,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'garlic-knots',
      name: 'Garlic Knots with Red Sauce',
      description: 'Fresh-baked garlic knots',
      price: 6.99,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'french-fries',
      name: 'French Fries',
      description: 'Crispy golden fries',
      price: 4.50,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'onion-rings',
      name: 'Onion Rings',
      description: 'Beer-battered onion rings',
      price: 5.50,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'jalapeno-poppers',
      name: 'Jalapeño Poppers',
      description: 'Stuffed with cream cheese',
      price: 8.99,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'garlic-bread',
      name: 'Garlic Bread',
      description: 'Fresh-baked with garlic butter',
      price: 4.50,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'garlic-bread-cheese',
      name: 'Garlic Bread with Cheese',
      description: 'With melted mozzarella',
      price: 4.99,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'garlic-spread',
      name: 'Garlic Spread',
      description: 'Garlic butter spread',
      price: 4.50,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'coleslaw',
      name: 'Coleslaw or Potato Salad',
      description: 'Side portion',
      price: 1.25,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'coleslaw-pint',
      name: 'Pint of Coleslaw or Potato Salad',
      description: 'Full pint',
      price: 2.50,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'meatball-side',
      name: 'Meatball Side',
      description: 'House-made meatballs',
      price: 4.50,
      category: 'appetizer',
    },
    {
      id: 'bag-sauce',
      name: 'Bag of Sauce',
      description: 'Extra marinara',
      price: 0.75,
      category: 'appetizer',
      isVegetarian: true,
    },
    {
      id: 'jojo-skins',
      name: 'Jo Jo Skins Cheese & Bacon',
      description: 'Loaded potato skins',
      price: 10.95,
      category: 'appetizer',
    },
    {
      id: 'sampler',
      name: 'Sampler',
      description: 'Assorted appetizers',
      price: 17.95,
      category: 'appetizer',
    },
    {
      id: 'chips',
      name: 'Chips',
      description: 'Bag of chips',
      price: 0.95,
      category: 'appetizer',
      isVegetarian: true,
    },
  ],
  desserts: [
    {
      id: 'cannoli',
      name: 'Cannoli',
      description: 'Crispy shell with sweet ricotta filling',
      price: 4.50,
      image: 'cannoli italian',
      category: 'dessert',
      isVegetarian: true,
    },
    {
      id: 'cheese-cake-9',
      name: 'Cheese Cake',
      description: 'Classic New York style (9" size)',
      price: 6.95,
      image: 'cheesecake slice',
      category: 'dessert',
      isVegetarian: true,
    },
    {
      id: 'carrot-cake',
      name: 'Carrot Cake',
      description: 'Moist carrot cake with cream cheese frosting',
      price: 6.95,
      image: 'carrot cake slice',
      category: 'dessert',
      isVegetarian: true,
    },
    {
      id: 'key-lime',
      name: 'Key Lime Pie',
      description: 'Tangy and sweet (3 sizes available)',
      price: 4.95,
      image: 'key lime pie',
      category: 'dessert',
      isVegetarian: true,
    },
    {
      id: 'cinnamon-knots',
      name: 'Homemade Frosted Cinnamon Knots',
      description: 'Fresh-baked cinnamon knots with frosting',
      price: 4.95,
      image: 'cinnamon rolls frosted',
      category: 'dessert',
      isVegetarian: true,
    },
  ],
  drinks: [
    {
      id: 'pepsi',
      name: 'Pepsi Products',
      description: 'Pepsi, Diet Pepsi, Mountain Dew, Dr Pepper, Orange, Lemonade, Unsweet Tea',
      price: 4.25,
      category: 'drink',
    },
  ],
  beers: [
    { id: 'ipa-1', name: 'Cigar City Jai Alai IPA', type: 'IPA', abv: 7.5, ibu: 70, pairing: 'Pepperoni or Meat Pie' },
    { id: 'lager-1', name: 'Yuengling Lager', type: 'Lager', abv: 4.5, ibu: 10, pairing: 'White Pizza' },
    { id: 'wheat-1', name: 'Blue Moon Belgian White', type: 'Wheat', abv: 5.4, ibu: 9, pairing: 'White Pizza' },
    { id: 'pale-1', name: 'Sierra Nevada Pale Ale', type: 'Pale Ale', abv: 5.6, ibu: 38, pairing: 'BBQ Chicken Pizza' },
    { id: 'stout-1', name: 'Left Hand Milk Stout', type: 'Stout', abv: 6.0, ibu: 25, pairing: 'Meat Pie' },
    { id: 'pilsner-1', name: 'Pilsner Urquell', type: 'Pilsner', abv: 4.4, ibu: 40, pairing: 'Classic Cheese' },
    { id: 'ipa-2', name: 'Funky Buddha Hop Gun IPA', type: 'IPA', abv: 7.5, ibu: 85, pairing: 'Buffalo Chicken Ranch' },
    { id: 'amber-1', name: 'Abita Amber', type: 'Amber', abv: 4.5, ibu: 18, pairing: 'The Works' },
    { id: 'porter-1', name: 'Founders Porter', type: 'Porter', abv: 6.5, ibu: 45, pairing: 'BBQ Chicken Pizza' },
    { id: 'hefeweizen-1', name: 'Paulaner Hefeweizen', type: 'Hefeweizen', abv: 5.5, ibu: 12, pairing: 'White Pizza' },
    { id: 'red-1', name: 'New Belgium Fat Tire', type: 'Amber Ale', abv: 5.2, ibu: 22, pairing: 'Any Pizza' },
    { id: 'sour-1', name: 'Dogfish Head SeaQuench', type: 'Sour', abv: 4.9, ibu: 10, pairing: 'Light pizzas' },
    { id: 'brown-1', name: 'Newcastle Brown Ale', type: 'Brown Ale', abv: 4.7, ibu: 25, pairing: 'Meat Pie' },
    { id: 'saison-1', name: 'Saison Dupont', type: 'Saison', abv: 6.5, ibu: 30, pairing: 'White Pizza' },
    { id: 'cider-1', name: 'Angry Orchard Crisp', type: 'Cider', abv: 5.0, ibu: 0, pairing: 'BBQ Chicken Pizza' },
    { id: 'lager-2', name: 'Stella Artois', type: 'Lager', abv: 5.0, ibu: 24, pairing: 'Any Pizza' },
    { id: 'ipa-3', name: '3 Daughters Beach Blonde', type: 'Blonde Ale', abv: 5.0, ibu: 15, pairing: 'The Works' },
    { id: 'specialty-1', name: 'Terrapin Hi-5 IPA', type: 'IPA', abv: 5.5, ibu: 55, pairing: 'Cheese Pizza' },
  ],
};

export const toppingCategories = {
  meats: [
    { id: 'pepperoni', name: 'Pepperoni', price: 1.75 },
    { id: 'sausage', name: 'Sausage', price: 1.75 },
    { id: 'meatballs', name: 'Meatballs', price: 2.50 },
    { id: 'ground-beef', name: 'Ground Beef', price: 1.75 },
    { id: 'ham', name: 'Ham', price: 1.75 },
    { id: 'bacon', name: 'Bacon', price: 2.50 },
  ],
  veggies: [
    { id: 'mushrooms', name: 'Mushrooms', price: 1.75 },
    { id: 'onions', name: 'Onions', price: 1.75 },
    { id: 'green-peppers', name: 'Green Peppers', price: 1.75 },
    { id: 'black-olives', name: 'Black Olives', price: 1.75 },
    { id: 'green-olives', name: 'Green Olives', price: 1.75 },
    { id: 'fresh-tomatoes', name: 'Fresh Tomatoes', price: 1.75 },
    { id: 'jalapeno', name: 'Jalapeño', price: 1.75 },
    { id: 'spinach', name: 'Spinach', price: 1.75 },
    { id: 'minced-garlic', name: 'Minced Garlic', price: 1.75 },
  ],
  premium: [
    { id: 'broccoli', name: 'Broccoli', price: 2.50 },
    { id: 'ricotta', name: 'Ricotta Cheese', price: 2.50 },
    { id: 'extra-cheese', name: 'Extra Cheese', price: 2.50 },
    { id: 'pineapple', name: 'Pineapple', price: 2.50 },
  ],
};

export const pizzaSizes = [
  { id: 'small', name: 'Small 10"', basePrice: 12.99, servings: '1-2' },
  { id: 'medium', name: 'Medium 14"', basePrice: 15.99, servings: '2-3' },
  { id: 'large', name: 'Large 18"', basePrice: 18.99, servings: '3-4' },
];

export const sauceOptions = [
  { id: 'red', name: 'Marinara Sauce' },
  { id: 'white', name: 'White Sauce (Ricotta Base)' },
  { id: 'bbq', name: 'BBQ Sauce' },
  { id: 'buffalo', name: 'Buffalo Sauce' },
  { id: 'garlic-oil', name: 'Garlic & Oil' },
];

export const cheeseOptions = [
  { id: 'regular', name: 'Regular Mozzarella' },
  { id: 'light', name: 'Light Cheese' },
  { id: 'extra', name: 'Extra Cheese (+$2.50)' },
  { id: 'none', name: 'No Cheese' },
];

export const testimonials = [
  {
    id: 1,
    name: 'Sarah M.',
    location: 'Taylor Park',
    text: 'Best pizza in Largo! Been coming here for 15 years and it never disappoints.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Mike D.',
    location: 'Disc Golf Regular',
    text: 'Perfect spot after a round at the disc golf course. The beer selection is incredible!',
    rating: 5,
  },
  {
    id: 3,
    name: 'Jennifer L.',
    location: 'Local Family',
    text: 'This place feels like home. My kids love the pizza and we love the gluten-free options!',
    rating: 5,
  },
];